FROM ubuntu:latest
MAINTAINER Marc PASTOR-ABAD "pastor_m@etna-alternance.net"
RUN apt-get update -y \
    && apt-get install -y python3-pip python3 build-essential
COPY . /app
WORKDIR /app
RUN pip3 install -r requirements.txt
ENTRYPOINT ["python3"]
CMD ["app.py"]
